### PR TITLE
Adapt to lts-8.6 and use proto-lens-0.2.0.0

### PR DESCRIPTION
**Pull request by jcberentsen**
Bumped to Stackage LTS-8.6, with proto-lens-0.2.0.0 and fixing compile errors.

### CODE REVIEW

**Comment by jcberentsen** [comment]
I signed it!

**Comment by blackgnezdo** [comment]
Jenkins test this please.

**Comment by judah** [comment]
Looks like the newest version of proto-lens has unnecessary warnings which are breaking the Jenkins build.  I'll send a PR and make a new release.

**Comment by judah** [comment]
I've uploaded proto-lens(-*)-0.2.0.1 and lens-labels-0.1.0.1 which should fix this build breakage.

**Comment by blackgnezdo** [comment]
@jcberentsen could you update your PR to the new versions an we can re-test it.

**Comment by jcberentsen** [comment]
I'll do that

Den man. 10. apr. 2017, 22:10 skrev Greg Steuck <notifications@github.com>:

@jcberentsen <https://github.com/jcberentsen> could you update your PR to
the new versions an we can re-test it.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/haskell/pull/94#issuecomment-293064503>, or mute
the thread

**Comment by judah** [comment]
Jenkins, test this please

**Comment by jcberentsen** [comment]
Hm, maybe I botched this up by merging from upstream? Should I drop this pull request and just make a new one with one amended commit?

**Comment by judah** [comment]
I think you can fix this PR by just rebasing and squashing everything against the current master, and then doing a `git push -f` to your branch.  But if it's easier for you to just make a new PR, that's OK too.

**Comment by jcberentsen** [comment]
I squashed the commits and made a new pull request.

**Pull request closed without merging**
