### PR TITLE
Bump version constraints for proto-lens-*

### PR DESCRIPTION
**Pull request by yorickvP**
I confirmed that it still builds with 0.5.

### CODE REVIEW

**Comment by yorickvP** [comment]
It would be great if there was a hackage release after merging this.

**Comment by blackgnezdo** [comment]
> It would be great if there was a hackage release after merging this.

We discussed this in #66, We don't know how to build this complicated library with cabal. If we were to publish as is we would get complaints about cabal not working.

Would it suffice if I put a tarball up on github?

**Comment by blackgnezdo** [comment]
> > It would be great if there was a hackage release after merging this.
> 
> We discussed this in #66, We don't know how to build this complicated library with cabal. If we were to publish as is we would get complaints about cabal not working.
> 
> Would it suffice if I put a tarball up on github?

Nevermind, I forgot that we did release it after all. I typo'd the search term...

**Comment by blackgnezdo** [comment]
Thanks for the change!

**Comment by blackgnezdo** [comment]
@judah do you have the publishing recipe handy?

**Comment by yorickvP** [comment]
If you're changing things on hackage, you should probably also remove tensorflow-mnist and tensorflow-mnist-input-data. It's not useful to have them available as packages

**Comment by judah** [comment]
I haven't touched this in a while, but I assume that the `stack upload` command should do the right thing for this project.

**Comment by yorickvP** [comment]
You'll need to update some version numbers and maybe constraints, too.

**Comment by blackgnezdo** [comment]
I uploaded a bunch of new packages. Let me know if anything is missing.

**Pull request merged**
