### PR TITLE
Added support for tanh activation function

### PR DESCRIPTION
**Pull request by rikvdkleij**
The CLA is signed by the manager of my company, Active Group GmbH. Please let me know if more info is needed.

### CODE REVIEW

**Comment by rikvdkleij** [comment]
My company signed it!

The email of the git commits is `rik.van.der.kleij@active.group@de` which is a member of the `active-group-google-contributors@googlegroups.com`

**Comment by fkm3** [comment]
Thanks for the contribution!

Did your company just sign the CLA? If so, we might need to wait a day or two for it to get processed. If not, I can ask someone why it isn't recognizing you.

**Comment by rikvdkleij** [comment]
@fkm3 Yes, it was just signed a few hours ago.

**Comment by rikvdkleij** [comment]
@fkm3 Any news about the CLA stuff?

**Comment by fkm3** [comment]
I think it went through now. Can you reply with "I signed it!" to make the bot re-run the check? Thanks!

**Comment by rikvdkleij** [comment]
I signed it!

**Comment by fkm3** [comment]
Now it says "CLAs are signed, but unable to verify author consent". Is the email used in the commit attached to your GitHub account?

Sorry that this is a pain...

**Comment by rikvdkleij** [comment]
No, the email of the commits is my email.The CLA is signed by the manager of Active Group GmbH. He is the owner of `active-group-google-contributors@googlegroups.com`. My email is a member of that Google group.

**Comment by fkm3** [comment]
I think you need to add your @active-group.de email to your @rikvdkleij github account: https://help.github.com/articles/adding-an-email-address-to-your-github-account/
(it doesn't need to be the primary, just verified)

**Comment by rikvdkleij** [comment]
@fkm3 Have done that. Thanks!

I will trigger the Google bot again.

**Comment by rikvdkleij** [comment]
I signed it!

**Comment by fkm3** [comment]
Success! Thanks for sticking with me.

**Pull request merged**
