### PR TITLE
added failing test

### PR DESCRIPTION
**Pull request by silky**
see https://github.com/tensorflow/haskell/issues/19

this fails. i expect that it should work and that it should result in the given output and shape.

~~once this test works, i'll need to make sure it actually properly checks the shape (at this point this can only be done correctly as a tensorflow op, because we can't yet get back multi-dim vectors https://github.com/tensorflow/haskell/issues/13)~~

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Jenkins test this please.

**Comment by silky** [comment]
as a side note, this other test that fails, the `Op TopK is not available in GraphDef version 15. It has been removed in version 7. Use TopKV2 instead` ... could probably be fixed. i'm not sure if you all see that when you run the tests locally, but i see it only when i have another test failing; it mysteriously goes away when it's the only test that fails.

**Comment by blackgnezdo** [comment]
Thanks for the test case! :+1:

I also just now noticed the TopKV2 issue. Let's see if we can crush these.

**Comment by silky** [comment]
i added a new commit to the source fixing the case when there is only a single partition

i also added a test that demonstrates that the multi-partition case is still broken

**Pull request merged**
