### PR TITLE
Preliminary support for TensorFlow 2

### PR DESCRIPTION
**Pull request by arrowd**
This PR adds some changes required to build against TF 2. It isn't sufficient still, the build now fails with following error message:

```
    Building library for tensorflow-core-ops-0.2.0.0..
    [1 of 1] Compiling TensorFlow.GenOps.Core ( .stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/global-autogen/TensorFlow/GenOps/Core.hs, .stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/TensorFlow/GenOps/Core.o )
    
    /usr/home/arr/projects/tf-haskell/tensorflow-core-ops/.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/global-autogen/TensorFlow/GenOps/Core.hs:24029:13: error:
        Variable not in scope: ncontext_sparse :: Int64
          |
    24029 |     pureOp [ncontext_sparse, ncontext_sparse, nfeature_list_sparse,
          |             ^^^^^^^^^^^^^^^
    
    /usr/home/arr/projects/tf-haskell/tensorflow-core-ops/.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/global-autogen/TensorFlow/GenOps/Core.hs:24029:30: error:
        Variable not in scope: ncontext_sparse :: Int64
          |
    24029 |     pureOp [ncontext_sparse, ncontext_sparse, nfeature_list_sparse,
          |                              ^^^^^^^^^^^^^^^
    
    /usr/home/arr/projects/tf-haskell/tensorflow-core-ops/.stack-work/dist/x86_64-freebsd-ino64/Cabal-2.4.0.1/build/global-autogen/TensorFlow/GenOps/Core.hs:24029:47: error:
        Variable not in scope: nfeature_list_sparse :: Int64
          |
    24029 |     pureOp [ncontext_sparse, ncontext_sparse, nfeature_list_sparse,
          |                                               ^^^^^^^^^^^^^^^^^^^^

```

Any input on how to proceed would be welcome.

### CODE REVIEW

**Comment by fkm3** [comment]
Hi.

It looks like the error is referencing the arguments of [ParseSequenceExample](https://github.com/tensorflow/tensorflow/blob/6f4a1bfbf2c2077d7c26112d8862737c1190f186/tensorflow/core/ops/parsing_ops.cc#L164). Maybe try adding that Op to the blacklist as an easy workaround.

I don't think we want to merge any TF2 changes until it has been released, but, if you run into any other road blocks trying to use it in the meantime, let us know and maybe we can help.

**Comment by arrowd** [comment]
> Hi.
> 
> It looks like the error is referencing the arguments of [ParseSequenceExample](https://github.com/tensorflow/tensorflow/blob/6f4a1bfbf2c2077d7c26112d8862737c1190f186/tensorflow/core/ops/parsing_ops.cc#L164). Maybe try adding that Op to the blacklist as an easy workaround.

Yep, that helped. It compiled successfully now.

> I don't think we want to merge any TF2 changes until it has been released, but, if you run into any other road blocks trying to use it in the meantime, let us know and maybe we can help.

Sure, I just wanted to share my work. Lets keep this PR open in the meantime.

**Comment by yorickvP** [comment]
This PR is also helpful for building with 1.13. Maybe parts should be merged so that's possible?

**Comment by fkm3** [comment]
Yeah, I'd definitely merge PR that fixes the build for 1.13.

Our tests currently run against 1.9, but that can be updated to 1.13 if needed: https://github.com/tensorflow/haskell/blob/master/ci_build/Dockerfile#L6

**Comment by blackgnezdo** [comment]
Resolved by #267.

**Pull request closed without merging**
