### PR TITLE
Build and Install in Ubuntu 16.04 without Docker

### PR DESCRIPTION
**Pull request by mohanr**
I have added the instructions that worked for me. 

The result is this.

       $ stack test   
tensorflow-0.1.0.0: test (suite: FFITest)
tensorflow-0.1.0.0: test (suite: VarIntTest)
tensorflow-core-ops-0.1.0.0: configure (lib)
tensorflow-core-ops-0.1.0.0: build (lib)
tensorflow-core-ops-0.1.0.0: copy/register
tensorflow-ops-0.1.0.0: configure (lib + test)
tensorflow-ops-0.1.0.0: build (lib + test)
tensorflow-ops-0.1.0.0: copy/register
tensorflow-mnist-0.1.0.0: configure (lib + exe + test)
tensorflow-mnist-0.1.0.0: build (lib + exe + test)
tensorflow-mnist-0.1.0.0: copy/register
tensorflow-mnist-0.1.0.0: test (suite: ParseTest)
tensorflow-nn-0.1.0.0: configure (lib + test)
tensorflow-nn-0.1.0.0: build (lib + test)
tensorflow-nn-0.1.0.0: copy/register
tensorflow-nn-0.1.0.0: test (suite: NNTest)
tensorflow-ops-0.1.0.0: test (suite: ArrayOpsTest)
tensorflow-ops-0.1.0.0: test (suite: BuildTest)
tensorflow-ops-0.1.0.0: test (suite: DataFlowOpsTest)
tensorflow-ops-0.1.0.0: test (suite: EmbeddingOpsTest)
tensorflow-ops-0.1.0.0: test (suite: GradientTest)
tensorflow-ops-0.1.0.0: test (suite: MiscTest)
tensorflow-ops-0.1.0.0: test (suite: OpsTest)
tensorflow-ops-0.1.0.0: test (suite: RegressionTest)
tensorflow-ops-0.1.0.0: test (suite: TracingTest)
tensorflow-ops-0.1.0.0: test (suite: TypesTest)
tensorflow-queue-0.1.0.0: configure (lib + test)
tensorflow-queue-0.1.0.0: build (lib + test)
tensorflow-queue-0.1.0.0: copy/register
tensorflow-queue-0.1.0.0: test (suite: QueueTest)
Log files have been written to: /home/mohan/Haskell/tensorflow-haskell/.stack-work/logs/
Completed 10 action(s).

### CODE REVIEW

**Comment by mohanr** [comment]
Some agreement I have to sign. I signed it!

**Comment by fkm3** [comment]
It might be useful to have these instructions as well since it seems like the binary distro isn't compiled with all of the bells and whistles enabled:

```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 
instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX in$
tructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 i$
structions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA in$
tructions, but these are available on your machine and could speed up CPU computations. 
```

**Comment by blackgnezdo** [comment]
I suspect some of this has to do with the non-final release status. I saw at least some commits having to do with enabling more CPU features. I'm not certain if we need to test the bazel recipe continuously. Thoughts?

Another observation: we should develop a story for accessing non-core ops from Haskell. This we will likely require the user to run bazel. I guess we can cross this bridge when there's somebody asking for it.

**Comment by fkm3** [comment]
Agreed that testing the bazel recipe continuously doesn't seem worth it.

**Comment by mohanr** [comment]
Noticed it but don't know at what stage. The installation process brought openjdk version "9-internal".

**Comment by blackgnezdo** [comment]
Openjdk is needed by Bazel. Not sure what "9-internal" is.

**Comment by blackgnezdo** [comment]
We are now building with Ubuntu 18.04 (due to tensorflow update). Please reopen with a newer Ubuntu if you still care.

**Pull request closed without merging**
