### PR TITLE
Upgraded to tensorflow 2.3

### PR DESCRIPTION
**Pull request by skynet1**
Upgraded the library to compile and be compatible with tensorflow 2.3

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Cool! Thank you.

Let's see if our CI passes.

**Comment by yorickvP** [comment]
The CI failed because stack.yaml needs an update to a newer resolver (lts-16.11? 16.19?).

**Comment by blackgnezdo** [comment]
Thanks @yorickvP!

@skynet1, the failure is:
```
Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for tensorflow-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow is a build target.

In the dependencies for tensorflow-core-ops-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow-core-ops is a build target.

In the dependencies for tensorflow-logging-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow-logging is a build target.

In the dependencies for tensorflow-mnist-0.1.0.0:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow-mnist is a build target.

In the dependencies for tensorflow-opgen-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow-opgen is a build target.

In the dependencies for tensorflow-ops-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
needed since tensorflow-ops is a build target.

In the dependencies for tensorflow-proto-0.2.0.1:
    proto-lens-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching version
                       is 0.7.0.0)
    proto-lens-protobuf-types-0.6.0.0 from stack configuration does not match ==0.7.*  (latest
                                      matching version is 0.7.0.0)
    proto-lens-runtime-0.6.0.0 from stack configuration does not match ==0.7.*  (latest matching
                               version is 0.7.0.0)
needed since tensorflow-proto is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true'
    in /root/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps in /tfhs/stack.yaml:

- proto-lens-0.7.0.0@sha256:2c44a62375f7712f9381f84b1d30cee2f94384f1c98801db2f4450359a8e5036,3036
- proto-lens-protobuf-types-0.7.0.0@sha256:e93fdb27d509b4d0886a2c45676267069c7b7036064372e938b8b6b7cceaecc9,2860
- proto-lens-runtime-0.7.0.0@sha256:d6cfab159a63f5c42a1a507638c674a714dfa5f69a06f559e8da840eaafde3ab,3115

Plan construction failed.
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 &&     apt-get update &&     apt-get install -y         libsnappy-dev         libncurses5-dev         libgmp-dev         libcurl3-dev         zlib1g-dev         curl         unzip         netbase         &&     curl -O -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz &&     tar zxf stack-2.1.3-linux-x86_64.tar.gz -C /usr/local/bin stack-2.1.3-linux-x86_64/stack --strip 1 &&     curl -O -L https://github.com/google/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip &&     unzip -d /usr/local protoc-3.9.1-linux-x86_64.zip bin/protoc &&     chmod 755 /usr/local/bin/protoc &&     curl -O https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz &&     tar zxf libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz -C /usr/local &&     ldconfig &&     stack setup &&     stack test --only-dependencies' returned a non-zero code: 1


[ID: 3363863] Build finished after 251 secs, exit value: 1

```

**Comment by blackgnezdo** [comment]
Resolved in #267.

**Pull request closed without merging**
