### PR TITLE
Update to TensorFlow 2.10.1

### PR DESCRIPTION
**Pull request by Minnozz**
- [x] Update submodule to 2.10.1
- [x] Update Dockerfiles in `docker/` and `ci_build/` to `tensorflow/tensorflow:2.10.1`
  - [x] Verify that `stack --docker test` succeeds
- [x] Update Nix integration to nixpkgs that contains `libtensorflow` 2.10.1
  - [x] Verify that `stack --nix test` succeeds
- [x] Update protobuf file list
- [x] [Use new byte layout for string tensors
](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0) (breaking change; fixes `QueueTest` in `tensorflow-ops`)

### CODE REVIEW

**Comment by Minnozz** [comment]
I'm not a user of TensorFlow; I updated these binding for a colleague who needed the SavedModel functionality.
Feedback or further contributions are welcome.

**Comment by fkm3** [comment]
Thanks for the PR, I'll try to review soon.

**Comment by fkm3** [comment]
I'm seeing some failures in `tensorflow-ops:GradientTest`. Running the CI to confirm. Are you seeing the same? Haven't had a chance to try debugging yet.

This PR does a couple things

* Updates to new TF version
* Updates to new GHC and Stack version
* Switches from TF_DeprecatedSession to TF_Session
* Adds support for SavedModel

I know sometimes things needs to happen together, but could you separate out at least the new feature (SavedModel support) if possible.

**Comment by Minnozz** [comment]
> I'm seeing some failures in `tensorflow-ops:GradientTest`. Running the CI to confirm. Are you seeing the same? Haven't had a chance to try debugging yet.

Yes, I see those too. I can't find any test output that indicates what's going wrong, so I'm not sure how to debug this further.

> 
> This PR does a couple things
> 
>     * Updates to new TF version
> 
>     * Updates to new GHC and Stack version
> 
>     * Switches from TF_DeprecatedSession to TF_Session
> 
>     * Adds support for SavedModel
> 
> 
> I know sometimes things needs to happen together, but could you separate out at least the new feature (SavedModel support) if possible.

Yes, now that I have a (mostly) working version I'll try to separate things out some more. SavedModel support depends on the new TF version (for TF_LoadSessionFromSavedModel) and on TF_Session (which is used by TF_LoadSessionFromSavedModel). I'll try to see if the new GHC and Stack versions are still required (it was one of the first things I tried to solve a compilation error).

**Comment by Minnozz** [comment]
@fkm3 Is there a way you would like to receive sequential PRs or should I wait with submitting the next one until the previous one is merged?

**Comment by fkm3** [comment]
Thanks!

> I could use some help with updating the byte layout of string tensors, which is the reason the QueueTest fails.

I'll try to figure it out. Thanks for narrowing it down

**Comment by Minnozz** [comment]
https://github.com/tensorflow/community/blob/master/rfcs/20190411-string-unification.md

**Comment by fkm3** [comment]
I think I've got a working solution at https://github.com/tensorflow/haskell/commit/63753cc20da7dbe8668106496f783923ccd6c370. Can you cherry pick that CL into this PR? (I either don't have permissions to push to this or I am doing it wrong)

**Comment by Minnozz** [comment]
@fkm3 Thanks for implementing the new TF_STRING format! I've replaced my placeholder commit with yours.

**Comment by Minnozz** [comment]
My remaining question is whether all the protos I added should be generated or if some of them are considered internal.

**Comment by fkm3** [comment]
I'm not sure. We could look at the `BUILD` files and check the visibility for the various proto files, but I'm not sure if it is worth the effort.

For the sake of compile times, it would be best to only add what we need. Not a blocker though, we can always trim it later and build time wise other parts of the library are much worse (I can't believe how slow this project builds, not sure if it was always this bad or if something regressed).

**Comment by fkm3** [comment]
There is a build error. It is my fault, forgot to test my commit with `--pedantic`

```
tensorflow                 > /[tfhs/tensorflow/src/TensorFlow/Types.hs:82](https://cs.corp.google.com/piper///depot/google3/tfhs/tensorflow/src/TensorFlow/Types.hs?l=82):1: error: [-Wunused-imports, -Werror=unused-imports]
tensorflow                 >     The qualified import of ‘Data.Attoparsec.ByteString’ is redundant
tensorflow                 >       except perhaps to import instances from ‘Data.Attoparsec.ByteString’
tensorflow                 >     To import instances alone, use: import Data.Attoparsec.ByteString()
tensorflow                 >    |
tensorflow                 > 82 | import qualified Data.Attoparsec.ByteString as Atto
tensorflow                 >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow                 > 
tensorflow                 > /[tfhs/tensorflow/src/TensorFlow/Types.hs:131](https://cs.corp.google.com/piper///depot/google3/tfhs/tensorflow/src/TensorFlow/Types.hs?l=131):1: error: [-Wunused-imports, -Werror=unused-imports]
tensorflow                 >     The import of ‘TensorFlow.Internal.VarInt’ is redundant
tensorflow                 >       except perhaps to import instances from ‘TensorFlow.Internal.VarInt’
tensorflow                 >     To import instances alone, use: import TensorFlow.Internal.VarInt()
tensorflow                 >     |
tensorflow                 > 131 | import TensorFlow.Internal.VarInt (getVarInt, putVarInt)
tensorflow                 >     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Do you mind amending it to delete those two imports?

**Review by fkm3 — APPROVED** [review]

**Comment by fkm3** [comment]
Thanks for the PR, first TF version update in over 2 years!

**Pull request merged**
