### PR TITLE
Update to tensorflow 1.6

### PR DESCRIPTION
**Pull request by jbransen**

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Thanks for PR, there are other places that need adjustment.

I recommend looking at #161 for a template.

**Comment by jbransen** [comment]
You're right, I'll look into it.

**Comment by jbransen** [comment]
Sorry, it's not going to work. For my project I only need `tensorflow-proto` and `tensorflow`, for which this works fine, but due to some changes the opsgen breaks, in ways that I can't easily seem to fix. And in the mean time there is already 1.7 RC1, so it makes sense to wait for the 1.7 release before updating the Haskell bindings now.

**Comment by fkm3** [comment]
I think I've worked out the kinks for 1.7. The changes are at https://github.com/fkm3/tensorflow-haskell/tree/tensorflow_1_7

Will sent for review after https://github.com/tensorflow/haskell/pull/184 is in.

**Pull request closed without merging**
